### DISCUSSION TITLE
New tc release 0.8.29

### DISCUSSION THREAD

**Discussion by rberger** [tc-functors/tc#11] [Announcements]
## New tc release 0.8.29

- Adds reserved_concurrency attribute to infra spec. tc also resolves conflict between provisioned and reserved concurrency. The latter wins (Thanks to @EricHarvey)
- tc doc --spec infra|build|function is self-documenting and shows the schema for various input specifications. Please use that to see if any feature or attribute is supported.
- Starting to add various serverless patterns using tc in examples (https://github.com/informed-labs/tc/tree/main/examples/patterns). 
- Can also use tc inspect to visualize these and other functors see screenshot: 
![inspector_samples](https://github.com/user-attachments/assets/361f6fa7-83a2-40d5-8c20-0be81d875774)
- Adds remote functions (experimental). This  is a simple feature that allows pulling functions from non-monorepos or outside of current git repo (techno-core). Something like
```
functions:
  shared: []
  remote:
    - foo:
        uri: https://github.com/foo/foo
    - bar:
        uri: git@github.com:informed-labs/bar.git
    - baz:
        uri: file:///home/baz/baz
```
- Potentially can support marketplace lambda arns in the future.
