### ISSUE TITLE
Implement route to event mapping

### ISSUE THREAD

**Issue by icylisper** [tc-functors/tc#20]
Implement the following mapping.  Route to event mapping could be used in cases where there are filters specific to event targets

Mapping:
````
routes:
  /foo:
     method: POST
     event: MyEvent

events:
  MyEvent:
     ...
````
