### ISSUE TITLE
Implement route to queue mapping

### ISSUE THREAD

**Issue by icylisper** [tc-functors/tc#21]
Implement the following mapping:

````
routes:
   /foo:
       method: POST
       queue: MyQueue

queues:
    MyQueue:
         function: bar
```

This is a common case where we need the requests queued and the http handler needs to be async
