### ISSUE TITLE
Implement function to event mapping

### ISSUE THREAD

**Issue by icylisper** [tc-functors/tc#22]
Implement the following mapping:

````
functions:
     foo:
           event: MyEvent

events:
    MyEvent:
         channel | mutation | function 

````

Currently, a function needs to explicitly output an event from within it's handler. We could use `destinations` to generate an event
