### ISSUE TITLE
Implement function - function mapping

### ISSUE THREAD

**Issue by icylisper** [tc-functors/tc#26]
While currently this is implemented using step-functions, we may need an option to specify the mechanism or orchestrator

```

functions:
   foo:
     function: bar::evented
   bar:
     function: baz
   baz:
     function: boo
```
