### ISSUE TITLE
Add pages component or entity

### ISSUE THREAD

**Issue by icylisper** [tc-functors/tc#33]
`pages` is an abstraction for static HTML/js/wasm assets served via Cloudfront and S3. 

```
pages:
   myapp:
       path: ./app
       domain: ...
```
