### ISSUE TITLE
Routing filters based on headers, paths or custom domains

### ISSUE THREAD

**Issue by icylisper** [tc-functors/tc#36]
Based on this blog/news https://aws.amazon.com/blogs/compute/dynamically-routing-requests-with-amazon-api-gateway-routing-rules/, we should be able to set routing filters - useful for A/B testing

```
routes:
  /api/foo:
        function: {{namespace}}_foo_{{sandbox}}
        filter: '$header.x-sandbox == {{sandbox}}'
```

Eric Harvey's suggestion: This opens up a lot of possibilities
e.g. a sort of opt-in AB testing, where customers choose to route certain traffic through more experimental code
or even for internal ingestion, being able to pass headers that route to specific sandboxes to do special processing
