### ISSUE TITLE
Entity names should be namespaced and sandboxed by default

### ISSUE THREAD

**Issue by icylisper** [tc-functors/tc#38]
In the following block, both `foo` and `bar` are valid. foo should be automatically `fqn`'d

```
events:
  MyEvent:
      functions:
          - foo
          - '{{namespace}}_bar_{{sandbox}}

```
