### ISSUE TITLE
Make Triggers and Schedules as special Events

### ISSUE THREAD

**Issue by icylisper** [tc-functors/tc#42]
```
events:
   Schedule/test:
      function foo

   Auth/CustomMessage:
      function: messenger
```

Where Schedule/ should be a schedule rule and Auth a cognito trigger
